### ISSUE TITLE
runtime error: unspecified launch failure

### ISSUE THREAD

**Issue by XiaoPeilun** [yelantingfeng/pyLucid#3]
你好，我在 win10 下运行 demo 的时候报错了，内容如下：

```
Traceback (most recent call last):
  File ".\demo.py", line 11, in <module>
    bg = paint(Iorg,np.array(Morg),False)
  File "D:\code\pyLucid\patchPaint.py", line 60, in paint
    pm.propagate(iters=match_iter,rand_search_radius=maxoff)
  File "D:\code\pyLucid\PatchMatch\PatchMatchCuda.py", line 200, in propagate
    get_blocks_for_dim(cols,threads)))
  File "C:\Local\Programs\Python\Python35\lib\site-packages\pycuda\driver.py", line 405, in function_call
    Context.synchronize()
pycuda._driver.LaunchError: cuCtxSynchronize failed: unspecified launch failure
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: unspecified launch failure
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: unspecified launch failure
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: unspecified launch failure
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: unspecified launch failure
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: unspecified launch failure
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: unspecified launch failure
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuMemFree failed: unspecified launch failure
PyCUDA WARNING: a clean-up operation failed (dead context maybe?)
cuModuleUnload failed: unspecified launch failure
```
请问是哪里的问题呢？

**Comment by yelantf** [comment]
我是在ubuntu上跑的，不太确定windows上面能否运行。你这个问题我认为是没有正确安装pycuda，你可以去pycuda下面问一下
